// Code generated by ent, DO NOT EDIT.

package eventregistration

import (
	"awe/ent/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.EventRegistration {
	return predicate.EventRegistration(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.EventRegistration {
	return predicate.EventRegistration(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.EventRegistration {
	return predicate.EventRegistration(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.EventRegistration {
	return predicate.EventRegistration(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.EventRegistration {
	return predicate.EventRegistration(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.EventRegistration {
	return predicate.EventRegistration(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.EventRegistration {
	return predicate.EventRegistration(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.EventRegistration {
	return predicate.EventRegistration(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.EventRegistration {
	return predicate.EventRegistration(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.EventRegistration {
	return predicate.EventRegistration(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.EventRegistration {
	return predicate.EventRegistration(sql.FieldEQ(FieldUpdatedAt, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.EventRegistration {
	return predicate.EventRegistration(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.EventRegistration {
	return predicate.EventRegistration(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.EventRegistration {
	return predicate.EventRegistration(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.EventRegistration {
	return predicate.EventRegistration(sql.FieldNotIn(FieldStatus, vs...))
}

// AttendanceStatusEQ applies the EQ predicate on the "attendance_status" field.
func AttendanceStatusEQ(v AttendanceStatus) predicate.EventRegistration {
	return predicate.EventRegistration(sql.FieldEQ(FieldAttendanceStatus, v))
}

// AttendanceStatusNEQ applies the NEQ predicate on the "attendance_status" field.
func AttendanceStatusNEQ(v AttendanceStatus) predicate.EventRegistration {
	return predicate.EventRegistration(sql.FieldNEQ(FieldAttendanceStatus, v))
}

// AttendanceStatusIn applies the In predicate on the "attendance_status" field.
func AttendanceStatusIn(vs ...AttendanceStatus) predicate.EventRegistration {
	return predicate.EventRegistration(sql.FieldIn(FieldAttendanceStatus, vs...))
}

// AttendanceStatusNotIn applies the NotIn predicate on the "attendance_status" field.
func AttendanceStatusNotIn(vs ...AttendanceStatus) predicate.EventRegistration {
	return predicate.EventRegistration(sql.FieldNotIn(FieldAttendanceStatus, vs...))
}

// RegistrationDataIsNil applies the IsNil predicate on the "registration_data" field.
func RegistrationDataIsNil() predicate.EventRegistration {
	return predicate.EventRegistration(sql.FieldIsNull(FieldRegistrationData))
}

// RegistrationDataNotNil applies the NotNil predicate on the "registration_data" field.
func RegistrationDataNotNil() predicate.EventRegistration {
	return predicate.EventRegistration(sql.FieldNotNull(FieldRegistrationData))
}

// FeedbackIsNil applies the IsNil predicate on the "feedback" field.
func FeedbackIsNil() predicate.EventRegistration {
	return predicate.EventRegistration(sql.FieldIsNull(FieldFeedback))
}

// FeedbackNotNil applies the NotNil predicate on the "feedback" field.
func FeedbackNotNil() predicate.EventRegistration {
	return predicate.EventRegistration(sql.FieldNotNull(FieldFeedback))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.EventRegistration {
	return predicate.EventRegistration(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.EventRegistration {
	return predicate.EventRegistration(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.EventRegistration {
	return predicate.EventRegistration(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.EventRegistration {
	return predicate.EventRegistration(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.EventRegistration {
	return predicate.EventRegistration(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.EventRegistration {
	return predicate.EventRegistration(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.EventRegistration {
	return predicate.EventRegistration(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.EventRegistration {
	return predicate.EventRegistration(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.EventRegistration {
	return predicate.EventRegistration(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.EventRegistration {
	return predicate.EventRegistration(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.EventRegistration {
	return predicate.EventRegistration(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.EventRegistration {
	return predicate.EventRegistration(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.EventRegistration {
	return predicate.EventRegistration(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.EventRegistration {
	return predicate.EventRegistration(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.EventRegistration {
	return predicate.EventRegistration(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.EventRegistration {
	return predicate.EventRegistration(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasEvent applies the HasEdge predicate on the "event" edge.
func HasEvent() predicate.EventRegistration {
	return predicate.EventRegistration(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, EventTable, EventColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEventWith applies the HasEdge predicate on the "event" edge with a given conditions (other predicates).
func HasEventWith(preds ...predicate.Event) predicate.EventRegistration {
	return predicate.EventRegistration(func(s *sql.Selector) {
		step := newEventStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.EventRegistration {
	return predicate.EventRegistration(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.EventRegistration {
	return predicate.EventRegistration(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EventRegistration) predicate.EventRegistration {
	return predicate.EventRegistration(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EventRegistration) predicate.EventRegistration {
	return predicate.EventRegistration(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EventRegistration) predicate.EventRegistration {
	return predicate.EventRegistration(sql.NotPredicates(p))
}
