// Code generated by ent, DO NOT EDIT.

package programcategory

import (
	"awe/ent/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldLTE(FieldID, id))
}

// Slug applies equality check predicate on the "slug" field. It's identical to SlugEQ.
func Slug(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldEQ(FieldSlug, v))
}

// IconName applies equality check predicate on the "icon_name" field. It's identical to IconNameEQ.
func IconName(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldEQ(FieldIconName, v))
}

// DisplayOrder applies equality check predicate on the "display_order" field. It's identical to DisplayOrderEQ.
func DisplayOrder(v int) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldEQ(FieldDisplayOrder, v))
}

// Color applies equality check predicate on the "color" field. It's identical to ColorEQ.
func Color(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldEQ(FieldColor, v))
}

// HeroImageURL applies equality check predicate on the "hero_image_url" field. It's identical to HeroImageURLEQ.
func HeroImageURL(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldEQ(FieldHeroImageURL, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldEQ(FieldUpdatedAt, v))
}

// SlugEQ applies the EQ predicate on the "slug" field.
func SlugEQ(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldEQ(FieldSlug, v))
}

// SlugNEQ applies the NEQ predicate on the "slug" field.
func SlugNEQ(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldNEQ(FieldSlug, v))
}

// SlugIn applies the In predicate on the "slug" field.
func SlugIn(vs ...string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldIn(FieldSlug, vs...))
}

// SlugNotIn applies the NotIn predicate on the "slug" field.
func SlugNotIn(vs ...string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldNotIn(FieldSlug, vs...))
}

// SlugGT applies the GT predicate on the "slug" field.
func SlugGT(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldGT(FieldSlug, v))
}

// SlugGTE applies the GTE predicate on the "slug" field.
func SlugGTE(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldGTE(FieldSlug, v))
}

// SlugLT applies the LT predicate on the "slug" field.
func SlugLT(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldLT(FieldSlug, v))
}

// SlugLTE applies the LTE predicate on the "slug" field.
func SlugLTE(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldLTE(FieldSlug, v))
}

// SlugContains applies the Contains predicate on the "slug" field.
func SlugContains(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldContains(FieldSlug, v))
}

// SlugHasPrefix applies the HasPrefix predicate on the "slug" field.
func SlugHasPrefix(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldHasPrefix(FieldSlug, v))
}

// SlugHasSuffix applies the HasSuffix predicate on the "slug" field.
func SlugHasSuffix(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldHasSuffix(FieldSlug, v))
}

// SlugEqualFold applies the EqualFold predicate on the "slug" field.
func SlugEqualFold(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldEqualFold(FieldSlug, v))
}

// SlugContainsFold applies the ContainsFold predicate on the "slug" field.
func SlugContainsFold(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldContainsFold(FieldSlug, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldNotNull(FieldDescription))
}

// IconNameEQ applies the EQ predicate on the "icon_name" field.
func IconNameEQ(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldEQ(FieldIconName, v))
}

// IconNameNEQ applies the NEQ predicate on the "icon_name" field.
func IconNameNEQ(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldNEQ(FieldIconName, v))
}

// IconNameIn applies the In predicate on the "icon_name" field.
func IconNameIn(vs ...string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldIn(FieldIconName, vs...))
}

// IconNameNotIn applies the NotIn predicate on the "icon_name" field.
func IconNameNotIn(vs ...string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldNotIn(FieldIconName, vs...))
}

// IconNameGT applies the GT predicate on the "icon_name" field.
func IconNameGT(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldGT(FieldIconName, v))
}

// IconNameGTE applies the GTE predicate on the "icon_name" field.
func IconNameGTE(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldGTE(FieldIconName, v))
}

// IconNameLT applies the LT predicate on the "icon_name" field.
func IconNameLT(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldLT(FieldIconName, v))
}

// IconNameLTE applies the LTE predicate on the "icon_name" field.
func IconNameLTE(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldLTE(FieldIconName, v))
}

// IconNameContains applies the Contains predicate on the "icon_name" field.
func IconNameContains(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldContains(FieldIconName, v))
}

// IconNameHasPrefix applies the HasPrefix predicate on the "icon_name" field.
func IconNameHasPrefix(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldHasPrefix(FieldIconName, v))
}

// IconNameHasSuffix applies the HasSuffix predicate on the "icon_name" field.
func IconNameHasSuffix(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldHasSuffix(FieldIconName, v))
}

// IconNameIsNil applies the IsNil predicate on the "icon_name" field.
func IconNameIsNil() predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldIsNull(FieldIconName))
}

// IconNameNotNil applies the NotNil predicate on the "icon_name" field.
func IconNameNotNil() predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldNotNull(FieldIconName))
}

// IconNameEqualFold applies the EqualFold predicate on the "icon_name" field.
func IconNameEqualFold(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldEqualFold(FieldIconName, v))
}

// IconNameContainsFold applies the ContainsFold predicate on the "icon_name" field.
func IconNameContainsFold(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldContainsFold(FieldIconName, v))
}

// DisplayOrderEQ applies the EQ predicate on the "display_order" field.
func DisplayOrderEQ(v int) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldEQ(FieldDisplayOrder, v))
}

// DisplayOrderNEQ applies the NEQ predicate on the "display_order" field.
func DisplayOrderNEQ(v int) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldNEQ(FieldDisplayOrder, v))
}

// DisplayOrderIn applies the In predicate on the "display_order" field.
func DisplayOrderIn(vs ...int) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldIn(FieldDisplayOrder, vs...))
}

// DisplayOrderNotIn applies the NotIn predicate on the "display_order" field.
func DisplayOrderNotIn(vs ...int) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldNotIn(FieldDisplayOrder, vs...))
}

// DisplayOrderGT applies the GT predicate on the "display_order" field.
func DisplayOrderGT(v int) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldGT(FieldDisplayOrder, v))
}

// DisplayOrderGTE applies the GTE predicate on the "display_order" field.
func DisplayOrderGTE(v int) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldGTE(FieldDisplayOrder, v))
}

// DisplayOrderLT applies the LT predicate on the "display_order" field.
func DisplayOrderLT(v int) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldLT(FieldDisplayOrder, v))
}

// DisplayOrderLTE applies the LTE predicate on the "display_order" field.
func DisplayOrderLTE(v int) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldLTE(FieldDisplayOrder, v))
}

// ColorEQ applies the EQ predicate on the "color" field.
func ColorEQ(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldEQ(FieldColor, v))
}

// ColorNEQ applies the NEQ predicate on the "color" field.
func ColorNEQ(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldNEQ(FieldColor, v))
}

// ColorIn applies the In predicate on the "color" field.
func ColorIn(vs ...string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldIn(FieldColor, vs...))
}

// ColorNotIn applies the NotIn predicate on the "color" field.
func ColorNotIn(vs ...string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldNotIn(FieldColor, vs...))
}

// ColorGT applies the GT predicate on the "color" field.
func ColorGT(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldGT(FieldColor, v))
}

// ColorGTE applies the GTE predicate on the "color" field.
func ColorGTE(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldGTE(FieldColor, v))
}

// ColorLT applies the LT predicate on the "color" field.
func ColorLT(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldLT(FieldColor, v))
}

// ColorLTE applies the LTE predicate on the "color" field.
func ColorLTE(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldLTE(FieldColor, v))
}

// ColorContains applies the Contains predicate on the "color" field.
func ColorContains(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldContains(FieldColor, v))
}

// ColorHasPrefix applies the HasPrefix predicate on the "color" field.
func ColorHasPrefix(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldHasPrefix(FieldColor, v))
}

// ColorHasSuffix applies the HasSuffix predicate on the "color" field.
func ColorHasSuffix(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldHasSuffix(FieldColor, v))
}

// ColorEqualFold applies the EqualFold predicate on the "color" field.
func ColorEqualFold(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldEqualFold(FieldColor, v))
}

// ColorContainsFold applies the ContainsFold predicate on the "color" field.
func ColorContainsFold(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldContainsFold(FieldColor, v))
}

// HeroImageURLEQ applies the EQ predicate on the "hero_image_url" field.
func HeroImageURLEQ(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldEQ(FieldHeroImageURL, v))
}

// HeroImageURLNEQ applies the NEQ predicate on the "hero_image_url" field.
func HeroImageURLNEQ(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldNEQ(FieldHeroImageURL, v))
}

// HeroImageURLIn applies the In predicate on the "hero_image_url" field.
func HeroImageURLIn(vs ...string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldIn(FieldHeroImageURL, vs...))
}

// HeroImageURLNotIn applies the NotIn predicate on the "hero_image_url" field.
func HeroImageURLNotIn(vs ...string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldNotIn(FieldHeroImageURL, vs...))
}

// HeroImageURLGT applies the GT predicate on the "hero_image_url" field.
func HeroImageURLGT(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldGT(FieldHeroImageURL, v))
}

// HeroImageURLGTE applies the GTE predicate on the "hero_image_url" field.
func HeroImageURLGTE(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldGTE(FieldHeroImageURL, v))
}

// HeroImageURLLT applies the LT predicate on the "hero_image_url" field.
func HeroImageURLLT(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldLT(FieldHeroImageURL, v))
}

// HeroImageURLLTE applies the LTE predicate on the "hero_image_url" field.
func HeroImageURLLTE(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldLTE(FieldHeroImageURL, v))
}

// HeroImageURLContains applies the Contains predicate on the "hero_image_url" field.
func HeroImageURLContains(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldContains(FieldHeroImageURL, v))
}

// HeroImageURLHasPrefix applies the HasPrefix predicate on the "hero_image_url" field.
func HeroImageURLHasPrefix(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldHasPrefix(FieldHeroImageURL, v))
}

// HeroImageURLHasSuffix applies the HasSuffix predicate on the "hero_image_url" field.
func HeroImageURLHasSuffix(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldHasSuffix(FieldHeroImageURL, v))
}

// HeroImageURLIsNil applies the IsNil predicate on the "hero_image_url" field.
func HeroImageURLIsNil() predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldIsNull(FieldHeroImageURL))
}

// HeroImageURLNotNil applies the NotNil predicate on the "hero_image_url" field.
func HeroImageURLNotNil() predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldNotNull(FieldHeroImageURL))
}

// HeroImageURLEqualFold applies the EqualFold predicate on the "hero_image_url" field.
func HeroImageURLEqualFold(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldEqualFold(FieldHeroImageURL, v))
}

// HeroImageURLContainsFold applies the ContainsFold predicate on the "hero_image_url" field.
func HeroImageURLContainsFold(v string) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldContainsFold(FieldHeroImageURL, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasPrograms applies the HasEdge predicate on the "programs" edge.
func HasPrograms() predicate.ProgramCategory {
	return predicate.ProgramCategory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ProgramsTable, ProgramsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProgramsWith applies the HasEdge predicate on the "programs" edge with a given conditions (other predicates).
func HasProgramsWith(preds ...predicate.Program) predicate.ProgramCategory {
	return predicate.ProgramCategory(func(s *sql.Selector) {
		step := newProgramsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProgramCategory) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProgramCategory) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProgramCategory) predicate.ProgramCategory {
	return predicate.ProgramCategory(sql.NotPredicates(p))
}
