// Code generated by ent, DO NOT EDIT.

package ent

import (
	"awe/ent/ent/blockfaq"
	"awe/ent/ent/contentblock"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// BlockFaq is the model entity for the BlockFaq schema.
type BlockFaq struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// InternalName holds the value of the "internal_name" field.
	InternalName string `json:"internal_name,omitempty"`
	// Badge holds the value of the "badge" field.
	Badge map[string]string `json:"badge,omitempty"`
	// Title holds the value of the "title" field.
	Title map[string]string `json:"title,omitempty"`
	// Description holds the value of the "description" field.
	Description map[string]string `json:"description,omitempty"`
	// AllowMultipleOpen holds the value of the "allow_multiple_open" field.
	AllowMultipleOpen bool `json:"allow_multiple_open,omitempty"`
	// DefaultOpenFirst holds the value of the "default_open_first" field.
	DefaultOpenFirst bool `json:"default_open_first,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BlockFaqQuery when eager-loading is set.
	Edges                   BlockFaqEdges `json:"edges"`
	content_block_block_faq *int
	selectValues            sql.SelectValues
}

// BlockFaqEdges holds the relations/edges for other nodes in the graph.
type BlockFaqEdges struct {
	// ContentBlock holds the value of the content_block edge.
	ContentBlock *ContentBlock `json:"content_block,omitempty"`
	// Items holds the value of the items edge.
	Items []*FaqItem `json:"items,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ContentBlockOrErr returns the ContentBlock value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BlockFaqEdges) ContentBlockOrErr() (*ContentBlock, error) {
	if e.ContentBlock != nil {
		return e.ContentBlock, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: contentblock.Label}
	}
	return nil, &NotLoadedError{edge: "content_block"}
}

// ItemsOrErr returns the Items value or an error if the edge
// was not loaded in eager-loading.
func (e BlockFaqEdges) ItemsOrErr() ([]*FaqItem, error) {
	if e.loadedTypes[1] {
		return e.Items, nil
	}
	return nil, &NotLoadedError{edge: "items"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BlockFaq) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case blockfaq.FieldBadge, blockfaq.FieldTitle, blockfaq.FieldDescription:
			values[i] = new([]byte)
		case blockfaq.FieldAllowMultipleOpen, blockfaq.FieldDefaultOpenFirst:
			values[i] = new(sql.NullBool)
		case blockfaq.FieldID:
			values[i] = new(sql.NullInt64)
		case blockfaq.FieldInternalName:
			values[i] = new(sql.NullString)
		case blockfaq.FieldCreatedAt, blockfaq.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case blockfaq.ForeignKeys[0]: // content_block_block_faq
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BlockFaq fields.
func (_m *BlockFaq) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case blockfaq.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case blockfaq.FieldInternalName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field internal_name", values[i])
			} else if value.Valid {
				_m.InternalName = value.String
			}
		case blockfaq.FieldBadge:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field badge", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Badge); err != nil {
					return fmt.Errorf("unmarshal field badge: %w", err)
				}
			}
		case blockfaq.FieldTitle:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Title); err != nil {
					return fmt.Errorf("unmarshal field title: %w", err)
				}
			}
		case blockfaq.FieldDescription:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Description); err != nil {
					return fmt.Errorf("unmarshal field description: %w", err)
				}
			}
		case blockfaq.FieldAllowMultipleOpen:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field allow_multiple_open", values[i])
			} else if value.Valid {
				_m.AllowMultipleOpen = value.Bool
			}
		case blockfaq.FieldDefaultOpenFirst:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field default_open_first", values[i])
			} else if value.Valid {
				_m.DefaultOpenFirst = value.Bool
			}
		case blockfaq.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case blockfaq.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case blockfaq.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field content_block_block_faq", value)
			} else if value.Valid {
				_m.content_block_block_faq = new(int)
				*_m.content_block_block_faq = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BlockFaq.
// This includes values selected through modifiers, order, etc.
func (_m *BlockFaq) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryContentBlock queries the "content_block" edge of the BlockFaq entity.
func (_m *BlockFaq) QueryContentBlock() *ContentBlockQuery {
	return NewBlockFaqClient(_m.config).QueryContentBlock(_m)
}

// QueryItems queries the "items" edge of the BlockFaq entity.
func (_m *BlockFaq) QueryItems() *FaqItemQuery {
	return NewBlockFaqClient(_m.config).QueryItems(_m)
}

// Update returns a builder for updating this BlockFaq.
// Note that you need to call BlockFaq.Unwrap() before calling this method if this BlockFaq
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BlockFaq) Update() *BlockFaqUpdateOne {
	return NewBlockFaqClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BlockFaq entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BlockFaq) Unwrap() *BlockFaq {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BlockFaq is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BlockFaq) String() string {
	var builder strings.Builder
	builder.WriteString("BlockFaq(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("internal_name=")
	builder.WriteString(_m.InternalName)
	builder.WriteString(", ")
	builder.WriteString("badge=")
	builder.WriteString(fmt.Sprintf("%v", _m.Badge))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(fmt.Sprintf("%v", _m.Title))
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(fmt.Sprintf("%v", _m.Description))
	builder.WriteString(", ")
	builder.WriteString("allow_multiple_open=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllowMultipleOpen))
	builder.WriteString(", ")
	builder.WriteString("default_open_first=")
	builder.WriteString(fmt.Sprintf("%v", _m.DefaultOpenFirst))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// BlockFaqs is a parsable slice of BlockFaq.
type BlockFaqs []*BlockFaq
