// Code generated by ent, DO NOT EDIT.

package ent

import (
	"awe/ent/ent/blocktabs"
	"awe/ent/ent/contentblock"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// BlockTabs is the model entity for the BlockTabs schema.
type BlockTabs struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// InternalName holds the value of the "internal_name" field.
	InternalName string `json:"internal_name,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BlockTabsQuery when eager-loading is set.
	Edges                    BlockTabsEdges `json:"edges"`
	content_block_block_tabs *int
	selectValues             sql.SelectValues
}

// BlockTabsEdges holds the relations/edges for other nodes in the graph.
type BlockTabsEdges struct {
	// ContentBlock holds the value of the content_block edge.
	ContentBlock *ContentBlock `json:"content_block,omitempty"`
	// Items holds the value of the items edge.
	Items []*TabItem `json:"items,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ContentBlockOrErr returns the ContentBlock value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BlockTabsEdges) ContentBlockOrErr() (*ContentBlock, error) {
	if e.ContentBlock != nil {
		return e.ContentBlock, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: contentblock.Label}
	}
	return nil, &NotLoadedError{edge: "content_block"}
}

// ItemsOrErr returns the Items value or an error if the edge
// was not loaded in eager-loading.
func (e BlockTabsEdges) ItemsOrErr() ([]*TabItem, error) {
	if e.loadedTypes[1] {
		return e.Items, nil
	}
	return nil, &NotLoadedError{edge: "items"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BlockTabs) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case blocktabs.FieldID:
			values[i] = new(sql.NullInt64)
		case blocktabs.FieldInternalName:
			values[i] = new(sql.NullString)
		case blocktabs.FieldCreatedAt, blocktabs.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case blocktabs.ForeignKeys[0]: // content_block_block_tabs
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BlockTabs fields.
func (_m *BlockTabs) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case blocktabs.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case blocktabs.FieldInternalName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field internal_name", values[i])
			} else if value.Valid {
				_m.InternalName = value.String
			}
		case blocktabs.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case blocktabs.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case blocktabs.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field content_block_block_tabs", value)
			} else if value.Valid {
				_m.content_block_block_tabs = new(int)
				*_m.content_block_block_tabs = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BlockTabs.
// This includes values selected through modifiers, order, etc.
func (_m *BlockTabs) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryContentBlock queries the "content_block" edge of the BlockTabs entity.
func (_m *BlockTabs) QueryContentBlock() *ContentBlockQuery {
	return NewBlockTabsClient(_m.config).QueryContentBlock(_m)
}

// QueryItems queries the "items" edge of the BlockTabs entity.
func (_m *BlockTabs) QueryItems() *TabItemQuery {
	return NewBlockTabsClient(_m.config).QueryItems(_m)
}

// Update returns a builder for updating this BlockTabs.
// Note that you need to call BlockTabs.Unwrap() before calling this method if this BlockTabs
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BlockTabs) Update() *BlockTabsUpdateOne {
	return NewBlockTabsClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BlockTabs entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BlockTabs) Unwrap() *BlockTabs {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BlockTabs is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BlockTabs) String() string {
	var builder strings.Builder
	builder.WriteString("BlockTabs(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("internal_name=")
	builder.WriteString(_m.InternalName)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// BlockTabsSlice is a parsable slice of BlockTabs.
type BlockTabsSlice []*BlockTabs
