// Code generated by ent, DO NOT EDIT.

package ent

import (
	"awe/ent/ent/blockvolunteersignup"
	"awe/ent/ent/contentblock"
	"awe/ent/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BlockVolunteerSignupUpdate is the builder for updating BlockVolunteerSignup entities.
type BlockVolunteerSignupUpdate struct {
	config
	hooks    []Hook
	mutation *BlockVolunteerSignupMutation
}

// Where appends a list predicates to the BlockVolunteerSignupUpdate builder.
func (_u *BlockVolunteerSignupUpdate) Where(ps ...predicate.BlockVolunteerSignup) *BlockVolunteerSignupUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetInternalName sets the "internal_name" field.
func (_u *BlockVolunteerSignupUpdate) SetInternalName(v string) *BlockVolunteerSignupUpdate {
	_u.mutation.SetInternalName(v)
	return _u
}

// SetNillableInternalName sets the "internal_name" field if the given value is not nil.
func (_u *BlockVolunteerSignupUpdate) SetNillableInternalName(v *string) *BlockVolunteerSignupUpdate {
	if v != nil {
		_u.SetInternalName(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *BlockVolunteerSignupUpdate) SetTitle(v map[string]string) *BlockVolunteerSignupUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetDescription sets the "description" field.
func (_u *BlockVolunteerSignupUpdate) SetDescription(v map[string]string) *BlockVolunteerSignupUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *BlockVolunteerSignupUpdate) ClearDescription() *BlockVolunteerSignupUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetShowSkillsInput sets the "show_skills_input" field.
func (_u *BlockVolunteerSignupUpdate) SetShowSkillsInput(v bool) *BlockVolunteerSignupUpdate {
	_u.mutation.SetShowSkillsInput(v)
	return _u
}

// SetNillableShowSkillsInput sets the "show_skills_input" field if the given value is not nil.
func (_u *BlockVolunteerSignupUpdate) SetNillableShowSkillsInput(v *bool) *BlockVolunteerSignupUpdate {
	if v != nil {
		_u.SetShowSkillsInput(*v)
	}
	return _u
}

// SetShowAvailability sets the "show_availability" field.
func (_u *BlockVolunteerSignupUpdate) SetShowAvailability(v bool) *BlockVolunteerSignupUpdate {
	_u.mutation.SetShowAvailability(v)
	return _u
}

// SetNillableShowAvailability sets the "show_availability" field if the given value is not nil.
func (_u *BlockVolunteerSignupUpdate) SetNillableShowAvailability(v *bool) *BlockVolunteerSignupUpdate {
	if v != nil {
		_u.SetShowAvailability(*v)
	}
	return _u
}

// SetRequireBackground sets the "require_background" field.
func (_u *BlockVolunteerSignupUpdate) SetRequireBackground(v bool) *BlockVolunteerSignupUpdate {
	_u.mutation.SetRequireBackground(v)
	return _u
}

// SetNillableRequireBackground sets the "require_background" field if the given value is not nil.
func (_u *BlockVolunteerSignupUpdate) SetNillableRequireBackground(v *bool) *BlockVolunteerSignupUpdate {
	if v != nil {
		_u.SetRequireBackground(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BlockVolunteerSignupUpdate) SetUpdatedAt(v time.Time) *BlockVolunteerSignupUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetContentBlockID sets the "content_block" edge to the ContentBlock entity by ID.
func (_u *BlockVolunteerSignupUpdate) SetContentBlockID(id int) *BlockVolunteerSignupUpdate {
	_u.mutation.SetContentBlockID(id)
	return _u
}

// SetContentBlock sets the "content_block" edge to the ContentBlock entity.
func (_u *BlockVolunteerSignupUpdate) SetContentBlock(v *ContentBlock) *BlockVolunteerSignupUpdate {
	return _u.SetContentBlockID(v.ID)
}

// Mutation returns the BlockVolunteerSignupMutation object of the builder.
func (_u *BlockVolunteerSignupUpdate) Mutation() *BlockVolunteerSignupMutation {
	return _u.mutation
}

// ClearContentBlock clears the "content_block" edge to the ContentBlock entity.
func (_u *BlockVolunteerSignupUpdate) ClearContentBlock() *BlockVolunteerSignupUpdate {
	_u.mutation.ClearContentBlock()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BlockVolunteerSignupUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BlockVolunteerSignupUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BlockVolunteerSignupUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BlockVolunteerSignupUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BlockVolunteerSignupUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := blockvolunteersignup.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BlockVolunteerSignupUpdate) check() error {
	if _u.mutation.ContentBlockCleared() && len(_u.mutation.ContentBlockIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BlockVolunteerSignup.content_block"`)
	}
	return nil
}

func (_u *BlockVolunteerSignupUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(blockvolunteersignup.Table, blockvolunteersignup.Columns, sqlgraph.NewFieldSpec(blockvolunteersignup.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.InternalName(); ok {
		_spec.SetField(blockvolunteersignup.FieldInternalName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(blockvolunteersignup.FieldTitle, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(blockvolunteersignup.FieldDescription, field.TypeJSON, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(blockvolunteersignup.FieldDescription, field.TypeJSON)
	}
	if value, ok := _u.mutation.ShowSkillsInput(); ok {
		_spec.SetField(blockvolunteersignup.FieldShowSkillsInput, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ShowAvailability(); ok {
		_spec.SetField(blockvolunteersignup.FieldShowAvailability, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RequireBackground(); ok {
		_spec.SetField(blockvolunteersignup.FieldRequireBackground, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(blockvolunteersignup.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ContentBlockCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   blockvolunteersignup.ContentBlockTable,
			Columns: []string{blockvolunteersignup.ContentBlockColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contentblock.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ContentBlockIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   blockvolunteersignup.ContentBlockTable,
			Columns: []string{blockvolunteersignup.ContentBlockColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contentblock.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{blockvolunteersignup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BlockVolunteerSignupUpdateOne is the builder for updating a single BlockVolunteerSignup entity.
type BlockVolunteerSignupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BlockVolunteerSignupMutation
}

// SetInternalName sets the "internal_name" field.
func (_u *BlockVolunteerSignupUpdateOne) SetInternalName(v string) *BlockVolunteerSignupUpdateOne {
	_u.mutation.SetInternalName(v)
	return _u
}

// SetNillableInternalName sets the "internal_name" field if the given value is not nil.
func (_u *BlockVolunteerSignupUpdateOne) SetNillableInternalName(v *string) *BlockVolunteerSignupUpdateOne {
	if v != nil {
		_u.SetInternalName(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *BlockVolunteerSignupUpdateOne) SetTitle(v map[string]string) *BlockVolunteerSignupUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetDescription sets the "description" field.
func (_u *BlockVolunteerSignupUpdateOne) SetDescription(v map[string]string) *BlockVolunteerSignupUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *BlockVolunteerSignupUpdateOne) ClearDescription() *BlockVolunteerSignupUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetShowSkillsInput sets the "show_skills_input" field.
func (_u *BlockVolunteerSignupUpdateOne) SetShowSkillsInput(v bool) *BlockVolunteerSignupUpdateOne {
	_u.mutation.SetShowSkillsInput(v)
	return _u
}

// SetNillableShowSkillsInput sets the "show_skills_input" field if the given value is not nil.
func (_u *BlockVolunteerSignupUpdateOne) SetNillableShowSkillsInput(v *bool) *BlockVolunteerSignupUpdateOne {
	if v != nil {
		_u.SetShowSkillsInput(*v)
	}
	return _u
}

// SetShowAvailability sets the "show_availability" field.
func (_u *BlockVolunteerSignupUpdateOne) SetShowAvailability(v bool) *BlockVolunteerSignupUpdateOne {
	_u.mutation.SetShowAvailability(v)
	return _u
}

// SetNillableShowAvailability sets the "show_availability" field if the given value is not nil.
func (_u *BlockVolunteerSignupUpdateOne) SetNillableShowAvailability(v *bool) *BlockVolunteerSignupUpdateOne {
	if v != nil {
		_u.SetShowAvailability(*v)
	}
	return _u
}

// SetRequireBackground sets the "require_background" field.
func (_u *BlockVolunteerSignupUpdateOne) SetRequireBackground(v bool) *BlockVolunteerSignupUpdateOne {
	_u.mutation.SetRequireBackground(v)
	return _u
}

// SetNillableRequireBackground sets the "require_background" field if the given value is not nil.
func (_u *BlockVolunteerSignupUpdateOne) SetNillableRequireBackground(v *bool) *BlockVolunteerSignupUpdateOne {
	if v != nil {
		_u.SetRequireBackground(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BlockVolunteerSignupUpdateOne) SetUpdatedAt(v time.Time) *BlockVolunteerSignupUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetContentBlockID sets the "content_block" edge to the ContentBlock entity by ID.
func (_u *BlockVolunteerSignupUpdateOne) SetContentBlockID(id int) *BlockVolunteerSignupUpdateOne {
	_u.mutation.SetContentBlockID(id)
	return _u
}

// SetContentBlock sets the "content_block" edge to the ContentBlock entity.
func (_u *BlockVolunteerSignupUpdateOne) SetContentBlock(v *ContentBlock) *BlockVolunteerSignupUpdateOne {
	return _u.SetContentBlockID(v.ID)
}

// Mutation returns the BlockVolunteerSignupMutation object of the builder.
func (_u *BlockVolunteerSignupUpdateOne) Mutation() *BlockVolunteerSignupMutation {
	return _u.mutation
}

// ClearContentBlock clears the "content_block" edge to the ContentBlock entity.
func (_u *BlockVolunteerSignupUpdateOne) ClearContentBlock() *BlockVolunteerSignupUpdateOne {
	_u.mutation.ClearContentBlock()
	return _u
}

// Where appends a list predicates to the BlockVolunteerSignupUpdate builder.
func (_u *BlockVolunteerSignupUpdateOne) Where(ps ...predicate.BlockVolunteerSignup) *BlockVolunteerSignupUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BlockVolunteerSignupUpdateOne) Select(field string, fields ...string) *BlockVolunteerSignupUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BlockVolunteerSignup entity.
func (_u *BlockVolunteerSignupUpdateOne) Save(ctx context.Context) (*BlockVolunteerSignup, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BlockVolunteerSignupUpdateOne) SaveX(ctx context.Context) *BlockVolunteerSignup {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BlockVolunteerSignupUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BlockVolunteerSignupUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BlockVolunteerSignupUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := blockvolunteersignup.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BlockVolunteerSignupUpdateOne) check() error {
	if _u.mutation.ContentBlockCleared() && len(_u.mutation.ContentBlockIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BlockVolunteerSignup.content_block"`)
	}
	return nil
}

func (_u *BlockVolunteerSignupUpdateOne) sqlSave(ctx context.Context) (_node *BlockVolunteerSignup, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(blockvolunteersignup.Table, blockvolunteersignup.Columns, sqlgraph.NewFieldSpec(blockvolunteersignup.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BlockVolunteerSignup.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, blockvolunteersignup.FieldID)
		for _, f := range fields {
			if !blockvolunteersignup.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != blockvolunteersignup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.InternalName(); ok {
		_spec.SetField(blockvolunteersignup.FieldInternalName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(blockvolunteersignup.FieldTitle, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(blockvolunteersignup.FieldDescription, field.TypeJSON, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(blockvolunteersignup.FieldDescription, field.TypeJSON)
	}
	if value, ok := _u.mutation.ShowSkillsInput(); ok {
		_spec.SetField(blockvolunteersignup.FieldShowSkillsInput, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ShowAvailability(); ok {
		_spec.SetField(blockvolunteersignup.FieldShowAvailability, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RequireBackground(); ok {
		_spec.SetField(blockvolunteersignup.FieldRequireBackground, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(blockvolunteersignup.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ContentBlockCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   blockvolunteersignup.ContentBlockTable,
			Columns: []string{blockvolunteersignup.ContentBlockColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contentblock.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ContentBlockIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   blockvolunteersignup.ContentBlockTable,
			Columns: []string{blockvolunteersignup.ContentBlockColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contentblock.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BlockVolunteerSignup{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{blockvolunteersignup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
