// Code generated by ent, DO NOT EDIT.

package ent

import (
	"awe/ent/ent/blockdivider"
	"awe/ent/ent/contentblock"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// BlockDivider is the model entity for the BlockDivider schema.
type BlockDivider struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// InternalName holds the value of the "internal_name" field.
	InternalName string `json:"internal_name,omitempty"`
	// Height holds the value of the "height" field.
	Height int `json:"height,omitempty"`
	// Color holds the value of the "color" field.
	Color string `json:"color,omitempty"`
	// Style holds the value of the "style" field.
	Style string `json:"style,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BlockDividerQuery when eager-loading is set.
	Edges                       BlockDividerEdges `json:"edges"`
	content_block_block_divider *int
	selectValues                sql.SelectValues
}

// BlockDividerEdges holds the relations/edges for other nodes in the graph.
type BlockDividerEdges struct {
	// ContentBlock holds the value of the content_block edge.
	ContentBlock *ContentBlock `json:"content_block,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ContentBlockOrErr returns the ContentBlock value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BlockDividerEdges) ContentBlockOrErr() (*ContentBlock, error) {
	if e.ContentBlock != nil {
		return e.ContentBlock, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: contentblock.Label}
	}
	return nil, &NotLoadedError{edge: "content_block"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BlockDivider) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case blockdivider.FieldID, blockdivider.FieldHeight:
			values[i] = new(sql.NullInt64)
		case blockdivider.FieldInternalName, blockdivider.FieldColor, blockdivider.FieldStyle:
			values[i] = new(sql.NullString)
		case blockdivider.FieldCreatedAt, blockdivider.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case blockdivider.ForeignKeys[0]: // content_block_block_divider
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BlockDivider fields.
func (_m *BlockDivider) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case blockdivider.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case blockdivider.FieldInternalName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field internal_name", values[i])
			} else if value.Valid {
				_m.InternalName = value.String
			}
		case blockdivider.FieldHeight:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field height", values[i])
			} else if value.Valid {
				_m.Height = int(value.Int64)
			}
		case blockdivider.FieldColor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field color", values[i])
			} else if value.Valid {
				_m.Color = value.String
			}
		case blockdivider.FieldStyle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field style", values[i])
			} else if value.Valid {
				_m.Style = value.String
			}
		case blockdivider.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case blockdivider.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case blockdivider.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field content_block_block_divider", value)
			} else if value.Valid {
				_m.content_block_block_divider = new(int)
				*_m.content_block_block_divider = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BlockDivider.
// This includes values selected through modifiers, order, etc.
func (_m *BlockDivider) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryContentBlock queries the "content_block" edge of the BlockDivider entity.
func (_m *BlockDivider) QueryContentBlock() *ContentBlockQuery {
	return NewBlockDividerClient(_m.config).QueryContentBlock(_m)
}

// Update returns a builder for updating this BlockDivider.
// Note that you need to call BlockDivider.Unwrap() before calling this method if this BlockDivider
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BlockDivider) Update() *BlockDividerUpdateOne {
	return NewBlockDividerClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BlockDivider entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BlockDivider) Unwrap() *BlockDivider {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BlockDivider is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BlockDivider) String() string {
	var builder strings.Builder
	builder.WriteString("BlockDivider(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("internal_name=")
	builder.WriteString(_m.InternalName)
	builder.WriteString(", ")
	builder.WriteString("height=")
	builder.WriteString(fmt.Sprintf("%v", _m.Height))
	builder.WriteString(", ")
	builder.WriteString("color=")
	builder.WriteString(_m.Color)
	builder.WriteString(", ")
	builder.WriteString("style=")
	builder.WriteString(_m.Style)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// BlockDividers is a parsable slice of BlockDivider.
type BlockDividers []*BlockDivider
