// Code generated by ent, DO NOT EDIT.

package ent

import (
	"awe/ent/ent/blocknewslettersignup"
	"awe/ent/ent/contentblock"
	"awe/ent/ent/predicate"
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BlockNewsletterSignupQuery is the builder for querying BlockNewsletterSignup entities.
type BlockNewsletterSignupQuery struct {
	config
	ctx              *QueryContext
	order            []blocknewslettersignup.OrderOption
	inters           []Interceptor
	predicates       []predicate.BlockNewsletterSignup
	withContentBlock *ContentBlockQuery
	withFKs          bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BlockNewsletterSignupQuery builder.
func (_q *BlockNewsletterSignupQuery) Where(ps ...predicate.BlockNewsletterSignup) *BlockNewsletterSignupQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *BlockNewsletterSignupQuery) Limit(limit int) *BlockNewsletterSignupQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *BlockNewsletterSignupQuery) Offset(offset int) *BlockNewsletterSignupQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *BlockNewsletterSignupQuery) Unique(unique bool) *BlockNewsletterSignupQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *BlockNewsletterSignupQuery) Order(o ...blocknewslettersignup.OrderOption) *BlockNewsletterSignupQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryContentBlock chains the current query on the "content_block" edge.
func (_q *BlockNewsletterSignupQuery) QueryContentBlock() *ContentBlockQuery {
	query := (&ContentBlockClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(blocknewslettersignup.Table, blocknewslettersignup.FieldID, selector),
			sqlgraph.To(contentblock.Table, contentblock.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, blocknewslettersignup.ContentBlockTable, blocknewslettersignup.ContentBlockColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first BlockNewsletterSignup entity from the query.
// Returns a *NotFoundError when no BlockNewsletterSignup was found.
func (_q *BlockNewsletterSignupQuery) First(ctx context.Context) (*BlockNewsletterSignup, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{blocknewslettersignup.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *BlockNewsletterSignupQuery) FirstX(ctx context.Context) *BlockNewsletterSignup {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BlockNewsletterSignup ID from the query.
// Returns a *NotFoundError when no BlockNewsletterSignup ID was found.
func (_q *BlockNewsletterSignupQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{blocknewslettersignup.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *BlockNewsletterSignupQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BlockNewsletterSignup entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one BlockNewsletterSignup entity is found.
// Returns a *NotFoundError when no BlockNewsletterSignup entities are found.
func (_q *BlockNewsletterSignupQuery) Only(ctx context.Context) (*BlockNewsletterSignup, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{blocknewslettersignup.Label}
	default:
		return nil, &NotSingularError{blocknewslettersignup.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *BlockNewsletterSignupQuery) OnlyX(ctx context.Context) *BlockNewsletterSignup {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BlockNewsletterSignup ID in the query.
// Returns a *NotSingularError when more than one BlockNewsletterSignup ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *BlockNewsletterSignupQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{blocknewslettersignup.Label}
	default:
		err = &NotSingularError{blocknewslettersignup.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *BlockNewsletterSignupQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BlockNewsletterSignups.
func (_q *BlockNewsletterSignupQuery) All(ctx context.Context) ([]*BlockNewsletterSignup, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*BlockNewsletterSignup, *BlockNewsletterSignupQuery]()
	return withInterceptors[[]*BlockNewsletterSignup](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *BlockNewsletterSignupQuery) AllX(ctx context.Context) []*BlockNewsletterSignup {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BlockNewsletterSignup IDs.
func (_q *BlockNewsletterSignupQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(blocknewslettersignup.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *BlockNewsletterSignupQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *BlockNewsletterSignupQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*BlockNewsletterSignupQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *BlockNewsletterSignupQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *BlockNewsletterSignupQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *BlockNewsletterSignupQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BlockNewsletterSignupQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *BlockNewsletterSignupQuery) Clone() *BlockNewsletterSignupQuery {
	if _q == nil {
		return nil
	}
	return &BlockNewsletterSignupQuery{
		config:           _q.config,
		ctx:              _q.ctx.Clone(),
		order:            append([]blocknewslettersignup.OrderOption{}, _q.order...),
		inters:           append([]Interceptor{}, _q.inters...),
		predicates:       append([]predicate.BlockNewsletterSignup{}, _q.predicates...),
		withContentBlock: _q.withContentBlock.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithContentBlock tells the query-builder to eager-load the nodes that are connected to
// the "content_block" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *BlockNewsletterSignupQuery) WithContentBlock(opts ...func(*ContentBlockQuery)) *BlockNewsletterSignupQuery {
	query := (&ContentBlockClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withContentBlock = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		InternalName string `json:"internal_name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BlockNewsletterSignup.Query().
//		GroupBy(blocknewslettersignup.FieldInternalName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *BlockNewsletterSignupQuery) GroupBy(field string, fields ...string) *BlockNewsletterSignupGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BlockNewsletterSignupGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = blocknewslettersignup.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		InternalName string `json:"internal_name,omitempty"`
//	}
//
//	client.BlockNewsletterSignup.Query().
//		Select(blocknewslettersignup.FieldInternalName).
//		Scan(ctx, &v)
func (_q *BlockNewsletterSignupQuery) Select(fields ...string) *BlockNewsletterSignupSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &BlockNewsletterSignupSelect{BlockNewsletterSignupQuery: _q}
	sbuild.label = blocknewslettersignup.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BlockNewsletterSignupSelect configured with the given aggregations.
func (_q *BlockNewsletterSignupQuery) Aggregate(fns ...AggregateFunc) *BlockNewsletterSignupSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *BlockNewsletterSignupQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !blocknewslettersignup.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *BlockNewsletterSignupQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*BlockNewsletterSignup, error) {
	var (
		nodes       = []*BlockNewsletterSignup{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withContentBlock != nil,
		}
	)
	if _q.withContentBlock != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, blocknewslettersignup.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*BlockNewsletterSignup).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &BlockNewsletterSignup{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withContentBlock; query != nil {
		if err := _q.loadContentBlock(ctx, query, nodes, nil,
			func(n *BlockNewsletterSignup, e *ContentBlock) { n.Edges.ContentBlock = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *BlockNewsletterSignupQuery) loadContentBlock(ctx context.Context, query *ContentBlockQuery, nodes []*BlockNewsletterSignup, init func(*BlockNewsletterSignup), assign func(*BlockNewsletterSignup, *ContentBlock)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*BlockNewsletterSignup)
	for i := range nodes {
		if nodes[i].content_block_block_newsletter_signup == nil {
			continue
		}
		fk := *nodes[i].content_block_block_newsletter_signup
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(contentblock.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "content_block_block_newsletter_signup" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *BlockNewsletterSignupQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *BlockNewsletterSignupQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(blocknewslettersignup.Table, blocknewslettersignup.Columns, sqlgraph.NewFieldSpec(blocknewslettersignup.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, blocknewslettersignup.FieldID)
		for i := range fields {
			if fields[i] != blocknewslettersignup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *BlockNewsletterSignupQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(blocknewslettersignup.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = blocknewslettersignup.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BlockNewsletterSignupGroupBy is the group-by builder for BlockNewsletterSignup entities.
type BlockNewsletterSignupGroupBy struct {
	selector
	build *BlockNewsletterSignupQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *BlockNewsletterSignupGroupBy) Aggregate(fns ...AggregateFunc) *BlockNewsletterSignupGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *BlockNewsletterSignupGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BlockNewsletterSignupQuery, *BlockNewsletterSignupGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *BlockNewsletterSignupGroupBy) sqlScan(ctx context.Context, root *BlockNewsletterSignupQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BlockNewsletterSignupSelect is the builder for selecting fields of BlockNewsletterSignup entities.
type BlockNewsletterSignupSelect struct {
	*BlockNewsletterSignupQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *BlockNewsletterSignupSelect) Aggregate(fns ...AggregateFunc) *BlockNewsletterSignupSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *BlockNewsletterSignupSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BlockNewsletterSignupQuery, *BlockNewsletterSignupSelect](ctx, _s.BlockNewsletterSignupQuery, _s, _s.inters, v)
}

func (_s *BlockNewsletterSignupSelect) sqlScan(ctx context.Context, root *BlockNewsletterSignupQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
