// Code generated by ent, DO NOT EDIT.

package blockpartnerlogos

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the blockpartnerlogos type in the database.
	Label = "block_partner_logos"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldInternalName holds the string denoting the internal_name field in the database.
	FieldInternalName = "internal_name"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldLayout holds the string denoting the layout field in the database.
	FieldLayout = "layout"
	// FieldItemsPerRow holds the string denoting the items_per_row field in the database.
	FieldItemsPerRow = "items_per_row"
	// FieldGrayscale holds the string denoting the grayscale field in the database.
	FieldGrayscale = "grayscale"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeContentBlock holds the string denoting the content_block edge name in mutations.
	EdgeContentBlock = "content_block"
	// EdgePartners holds the string denoting the partners edge name in mutations.
	EdgePartners = "partners"
	// Table holds the table name of the blockpartnerlogos in the database.
	Table = "block_partner_logos"
	// ContentBlockTable is the table that holds the content_block relation/edge.
	ContentBlockTable = "block_partner_logos"
	// ContentBlockInverseTable is the table name for the ContentBlock entity.
	// It exists in this package in order to avoid circular dependency with the "contentblock" package.
	ContentBlockInverseTable = "content_blocks"
	// ContentBlockColumn is the table column denoting the content_block relation/edge.
	ContentBlockColumn = "content_block_block_partner_logos"
	// PartnersTable is the table that holds the partners relation/edge.
	PartnersTable = "partner_logo_items"
	// PartnersInverseTable is the table name for the PartnerLogoItem entity.
	// It exists in this package in order to avoid circular dependency with the "partnerlogoitem" package.
	PartnersInverseTable = "partner_logo_items"
	// PartnersColumn is the table column denoting the partners relation/edge.
	PartnersColumn = "block_partner_logos_partners"
)

// Columns holds all SQL columns for blockpartnerlogos fields.
var Columns = []string{
	FieldID,
	FieldInternalName,
	FieldTitle,
	FieldDescription,
	FieldLayout,
	FieldItemsPerRow,
	FieldGrayscale,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "block_partner_logos"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"content_block_block_partner_logos",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultLayout holds the default value on creation for the "layout" field.
	DefaultLayout string
	// DefaultItemsPerRow holds the default value on creation for the "items_per_row" field.
	DefaultItemsPerRow int
	// DefaultGrayscale holds the default value on creation for the "grayscale" field.
	DefaultGrayscale bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the BlockPartnerLogos queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByInternalName orders the results by the internal_name field.
func ByInternalName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInternalName, opts...).ToFunc()
}

// ByLayout orders the results by the layout field.
func ByLayout(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLayout, opts...).ToFunc()
}

// ByItemsPerRow orders the results by the items_per_row field.
func ByItemsPerRow(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldItemsPerRow, opts...).ToFunc()
}

// ByGrayscale orders the results by the grayscale field.
func ByGrayscale(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGrayscale, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByContentBlockField orders the results by content_block field.
func ByContentBlockField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newContentBlockStep(), sql.OrderByField(field, opts...))
	}
}

// ByPartnersCount orders the results by partners count.
func ByPartnersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPartnersStep(), opts...)
	}
}

// ByPartners orders the results by partners terms.
func ByPartners(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPartnersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newContentBlockStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ContentBlockInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, ContentBlockTable, ContentBlockColumn),
	)
}
func newPartnersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PartnersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PartnersTable, PartnersColumn),
	)
}
